import puppeteer from "puppeteer";
const [,, out, sel] = process.argv;
const b = await puppeteer.launch({ headless:true, args:["--enable-unsafe-swiftshader","--use-gl=angle","--use-angle=swiftshader","--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width:1440, height:900, deviceScaleFactor:2 });
await p.goto("http://localhost:5173/", { waitUntil:"networkidle0" });
await new Promise(r=>setTimeout(r,2000));
await p.evaluate((s)=>document.querySelector(s)?.scrollIntoView({block:"start"}), sel);
await new Promise(r=>setTimeout(r,2500));
await p.screenshot({ path: out });
console.log("  saved", out);
await b.close();
